<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Newsletter_name</name>
   <tag></tag>
   <elementGuidId>25a65f58-784a-4e65-aecd-ceddcc0d2312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba91ca34-6730-4f6d-8ca9-55cda45e9819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11c42fac-6490-42dc-b463-6f7b4df833a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>0a35a916-d2be-4dbf-89f4-ac9dedf5c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newsletter_name form-control</value>
      <webElementGuid>a0c32545-2eb7-43db-878f-d9190b9bcf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;container mt-4 newsletter-section&quot;]/div[@class=&quot;rounded-4 p-4 bg-light&quot;]/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;form-floating&quot;]/input[@class=&quot;newsletter_name form-control&quot;]</value>
      <webElementGuid>e2c605bb-b48e-49ca-8020-b3c6871b3c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>003ea88d-7a11-4767-8af0-bb5cb1ba02ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[6]/div/div/div[2]/div/input</value>
      <webElementGuid>9bcf4d05-79b3-4b20-a7d1-a27968e0da63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/input</value>
      <webElementGuid>bab11e9f-3287-48a1-b9df-587e8eb0f9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name']</value>
      <webElementGuid>5fc3fcc4-1e7b-4ce3-aa4d-1ff3cd224834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
