<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_GBP</name>
   <tag></tag>
   <elementGuidId>bce13bf6-903c-4a40-bb38-c164aaa782f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div[2]/ul/li[2]/ul/li[2]/a/span/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.dropdown-item.fadeout.waves-effect > span > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>c0b18880-7aef-48d7-9aaf-ae7f03e4e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBP</value>
      <webElementGuid>ef3aed83-48ff-43fe-b4fa-7b586707d63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;nav-item--right&quot;]/ul[@class=&quot;navbar-nav gap-2 me-auto mb-2 mb-lg-0&quot;]/li[@class=&quot;nav-item dropdown&quot;]/ul[@class=&quot;dropdown-menu rounded-1 show&quot;]/li[2]/a[@class=&quot;dropdown-item fadeout waves-effect&quot;]/span[1]/strong[1]</value>
      <webElementGuid>b1f9b0be-b094-4c3f-aa41-b53659929f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div[2]/ul/li[2]/ul/li[2]/a/span/strong</value>
      <webElementGuid>73f67c20-0cc6-4e28-b4cf-38e411761d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/following::strong[1]</value>
      <webElementGuid>36b74611-0cc4-4514-b4f9-a93b23daa147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::strong[1]</value>
      <webElementGuid>c7dd37d6-0ed3-47e8-a01c-54dba75ec73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::strong[1]</value>
      <webElementGuid>fedb9b71-996b-43c6-9bee-fc93be569077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/preceding::strong[1]</value>
      <webElementGuid>54c74dc4-2e8c-472c-b7e4-2c87daeb9713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GBP']/parent::*</value>
      <webElementGuid>5cd8c301-931c-4124-b9da-32a000c284a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span/strong</value>
      <webElementGuid>e0907905-398b-479c-b861-8a85d9163d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'GBP' or . = 'GBP')]</value>
      <webElementGuid>ca30d425-decf-4899-aa55-9fdbe12937aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
