<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Childs_search_button w-100 btn btn-p_6519d4</name>
   <tag></tag>
   <elementGuidId>5922933f-1785-4588-9b1a-898f8f43f5ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cars-search > div.row.mb-0.pt-1.g-2.show.active > div.col-md-1 > button.search_button.w-100.btn.btn-primary.btn-m.rounded-sm.font-700.text-uppercase.btn-full.waves-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35614899-0ab1-401b-98e1-cfb38ae8e098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b065035a-b5fb-4776-b226-83fe0e208515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_button w-100 btn btn-primary btn-m rounded-sm font-700 text-uppercase btn-full waves-effect</value>
      <webElementGuid>176f6915-4e54-461a-89dc-f0f102d4dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cars-search&quot;)/div[@class=&quot;row mb-0 pt-1 g-2 show active&quot;]/div[@class=&quot;col-md-1&quot;]/button[@class=&quot;search_button w-100 btn btn-primary btn-m rounded-sm font-700 text-uppercase btn-full waves-effect&quot;]</value>
      <webElementGuid>85001bec-af35-4d51-bddc-a78d1ff00413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>f631bd0e-2e32-402d-b4ac-289a2ce685ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cars-search']/div/div[5]/button</value>
      <webElementGuid>224d457f-0093-483f-8945-612d8448bbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Hotels'])[1]/preceding::button[2]</value>
      <webElementGuid>60731357-a8aa-4cca-b28c-de5ccd71c7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::button[2]</value>
      <webElementGuid>75da24d1-eb95-4340-bf87-0f502b6ce5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div[5]/button</value>
      <webElementGuid>3083d609-ea40-4726-8ec6-605b197bb33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>79e2f64c-2c31-4c1b-84af-7332fe9c8111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
